@host = http://localhost:5223

DELETE {{host}}/Subject/DeleteSubject/5edddf98-50f5-4022-1516-08db2257270b
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiOGZhZjA5YS0zNTM5LTQ1N2MtYjU1Mi1hOTY1OWJhZWNjMTIiLCJnaXZlbl9uYW1lIjoiTGUiLCJmYW1pbHlfbmFtZSI6IkxlIiwianRpIjoiYWM0OTQ3MjQtNDU0Mi00YzQ0LThlNjUtYjI3Yzc5N2Y5ODljIiwiZXhwIjoxNjc4NjM3NTc1LCJpc3MiOiJDRUQtRGV2ZWxvcGVyIiwiYXVkIjoiQ0VELURldmVsb3BlciJ9.KGRANNdht8jFizcImcgaoHO6Vm6-qAfE0oRSzI6LEtM