@host = http://localhost:5223

Get {{host}}/Subject/GetAllSubjects
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzZTZjMGMwOC1lOTE1LTRkNzctOWI0MC1lOWM2NmQzZTQwNzciLCJnaXZlbl9uYW1lIjoiTGUiLCJmYW1pbHlfbmFtZSI6IkxlIiwianRpIjoiODY1NjNkODgtYjY1My00NWY3LWFiZjEtODAzNzI4YzM4ZGEwIiwiZXhwIjoxNjc4NTU5MDc0LCJpc3MiOiJDRUQtRGV2ZWxvcGVyIiwiYXVkIjoiQ0VELURldmVsb3BlciJ9._9XgagJxbULJDGBLJfWsXThLCgLjmK3lVxiTAwBC2g8
