@host = http://localhost:5223

Get {{host}}/api/Subject/GetAllSubjects
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiOGZhZjA5YS0zNTM5LTQ1N2MtYjU1Mi1hOTY1OWJhZWNjMTIiLCJnaXZlbl9uYW1lIjoiTGUiLCJmYW1pbHlfbmFtZSI6IkxlIiwianRpIjoiN2JkNDNlZmItZjJmZS00ZDIxLWE3N2UtZjJkMjkxYTE5OTAwIiwiZXhwIjoxNjc4NzY5MjI0LCJpc3MiOiJDRUQtRGV2ZWxvcGVyIiwiYXVkIjoiQ0VELURldmVsb3BlciJ9.MohRQUFmXgq3ApIpNLOhLZhk5okvRmBaKBzitw-t3YE

###
@host = http://localhost:5223

Get {{host}}/api/Subject/GetSubject/d14b23af-15bd-4dd5-151c-08db2257270b
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiOGZhZjA5YS0zNTM5LTQ1N2MtYjU1Mi1hOTY1OWJhZWNjMTIiLCJnaXZlbl9uYW1lIjoiTGUiLCJmYW1pbHlfbmFtZSI6IkxlIiwianRpIjoiODEwNjcwZTMtNzY1ZC00YjhjLThjMGUtNGVjZTgzYWIzYmVlIiwiZXhwIjoxNjc4NzcwNTA5LCJpc3MiOiJDRUQtRGV2ZWxvcGVyIiwiYXVkIjoiQ0VELURldmVsb3BlciJ9.NbSV7TuA0cWjwOfjj0WfOPiMu6rLJiYwDzq-RofuRmU
