@host = http://localhost:5223

Get {{host}}/api/ClassInformation/GetAllClassInformations
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiOGZhZjA5YS0zNTM5LTQ1N2MtYjU1Mi1hOTY1OWJhZWNjMTIiLCJnaXZlbl9uYW1lIjoiTGUiLCJmYW1pbHlfbmFtZSI6IkxlIiwianRpIjoiMjBmMzZiNzUtYTYyMi00NmM1LTk4OTItZjBkYWFjMWY3ZTI5IiwiZXhwIjoxNjc4NzY5ODczLCJpc3MiOiJDRUQtRGV2ZWxvcGVyIiwiYXVkIjoiQ0VELURldmVsb3BlciJ9.jeGU7IQLxUihx6-ZJbQSIDh0_V1bo3OGMIx3GnLzxik

###
@host = http://localhost:5223

Get {{host}}/api/ClassInformation/GetClassInformation/8ad637b3-c133-442f-0599-08db24405582
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiOGZhZjA5YS0zNTM5LTQ1N2MtYjU1Mi1hOTY1OWJhZWNjMTIiLCJnaXZlbl9uYW1lIjoiTGUiLCJmYW1pbHlfbmFtZSI6IkxlIiwianRpIjoiODEwNjcwZTMtNzY1ZC00YjhjLThjMGUtNGVjZTgzYWIzYmVlIiwiZXhwIjoxNjc4NzcwNTA5LCJpc3MiOiJDRUQtRGV2ZWxvcGVyIiwiYXVkIjoiQ0VELURldmVsb3BlciJ9.NbSV7TuA0cWjwOfjj0WfOPiMu6rLJiYwDzq-RofuRmU