@host = http://localhost:5223

DELETE {{host}}/api/ClassInformation/DeleteClassInformation/8ad637b3-c133-442f-0599-08db24405582
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiOGZhZjA5YS0zNTM5LTQ1N2MtYjU1Mi1hOTY1OWJhZWNjMTIiLCJnaXZlbl9uYW1lIjoiTGUiLCJmYW1pbHlfbmFtZSI6IkxlIiwianRpIjoiYWM0OTQ3MjQtNDU0Mi00YzQ0LThlNjUtYjI3Yzc5N2Y5ODljIiwiZXhwIjoxNjc4NjM3NTc1LCJpc3MiOiJDRUQtRGV2ZWxvcGVyIiwiYXVkIjoiQ0VELURldmVsb3BlciJ9.KGRANNdht8jFizcImcgaoHO6Vm6-qAfE0oRSzI6LEtM