@host = http://localhost:5223

Post {{host}}/Subject/UpdateSubject
Content-Type: application/json
Authorization: Bearer  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiOGZhZjA5YS0zNTM5LTQ1N2MtYjU1Mi1hOTY1OWJhZWNjMTIiLCJnaXZlbl9uYW1lIjoiTGUiLCJmYW1pbHlfbmFtZSI6IkxlIiwianRpIjoiNGFmODdlZTUtMTAwZi00M2YxLWIzNDQtOGMwZDk0MGZhNTE4IiwiZXhwIjoxNjc4NjQxODk2LCJpc3MiOiJDRUQtRGV2ZWxvcGVyIiwiYXVkIjoiQ0VELURldmVsb3BlciJ9.MqrLqnwAK8BNtqlQLalsRt4k3CsZxMdElpBUD_L_v9k

{
  "name": "Nino",
  "description": "Olivettotototo",
  "isDeleted": false,
  "deleterUserId": null,
  "deletionTime": null,
  "lastModificationTime": null,
  "lastModifierUserId": null,
  "creationTime": "2023-03-12T00:36:31.5410204",
  "creatorUserId": null,
  "id": "d14b23af-15bd-4dd5-151c-08db2257270b"
}
